study_design:
  - "Randomized controlled trial"
  - "Prospective cohort"
  - "Retrospective cohort"
  - "Cross-sectional study"
  - "Case-control study"
  - "Systematic review"
  - "Case series"
  - "Case report"
  - "Preclinical Experimental"
  - "Other"

subspecialty_focus:
  - "Aesthetic / Cosmetic (non-breast)"
  - "Breast"
  - "Craniofacial"
  - "Hand/Upper extremity & Peripheral Nerve"
  - "Burn"
  - "Generalized Cutaneous Disorders"
  - "Head & Neck Reconstruction"
  - "Trunk / Pelvic / Lower-Limb Reconstruction"
  - "Gender-affirming Surgery"
  - "Education & Technology"
  - "Other"

priority_topic:
  - "Gluteal Fat Grafting Safety (incl. BBL mortality risk)"
  - "Liposuction Safety"
  - "ADM (Acellular Dermal Matrix) Safety Updates"
  - "Injectable Fillers Safety"
  - "Malignant Hyperthermia"
  - "Ambulatory Surgery Adverse Event Prevention"
  - "Breast Implant-Associated Anaplastic Large Cell Lymphoma (BIA-ALCL)"
  - "FDA Warning: Silicone Injection"
  - "Administration of Botulinum Toxin Neuromodulators"
  - "Breast Augmentation in Teenagers"
  - "Social Media Ethics"
  - "Artificial Intelligence (AI) in Plastic Surgery"
  - "Telemedicine and Virtual Care"
  - "Regenerative Medicine (incl. Stem Cells and Fat Grafting)"
  - "Opioid Prescribing"
  - "Economic Evaluations"
  - "Breast Cancer Patient Education Act"
  - "Ensuring Lasting Smiles Act"
  - "Global Surgery / Access to Reconstructive Care"
  - "Diversity, Equity, and Inclusion (DEI)"
  - "Resident and Physician Wellness"
  - "Migraine Headache Surgery"
  - "Overseas Surgery Complications and Ethics"
  - "Other"

