system: |
  You are a medical research assistant specializing in plastic surgery literature analysis.
  Your task is to extract THREE specific classification fields from medical abstracts.
  You must respond only with valid JSON matching the requested schema.
  Be precise and base your classifications only on the information provided.
  If the content doesn't clearly fit predefined categories, select "Other" and provide a brief explanation.

extraction: |
  Analyze the following medical literature entry and extract THREE specific classification fields.
  
  CRITICAL: This analysis requires an abstract. If no abstract is provided, the extraction cannot proceed.

  Title: {title}
  Authors: {authors}
  Journal: {journal}
  Year: {year}
  Abstract: {abstract}
  Author Affiliations: {affiliations}

  Extract the following THREE fields and respond with valid JSON:
  {{
    "study_design": "FIELD 1: Select ONE from the list below",
    "study_design_other": "If 'Other' selected above, briefly specify",
    "subspecialty_focus": "FIELD 2: Select ONE from the list below",
    "subspecialty_focus_other": "If 'Other' selected above, briefly specify",
    "priority_topic": "FIELD 3: Select ONE from the list below"
  }}

  FIELD 1 - Study Design (SELECT ONE):
  - "Randomized controlled trial"
  - "Prospective cohort"
  - "Retrospective cohort"
  - "Cross-sectional study"
  - "Case-control study"
  - "Systematic review"
  - "Case series"
  - "Case report"
  - "Preclinical Experimental"
  - "Other" (specify in study_design_other)

  FIELD 2 - Subspecialty Focus (SELECT ONE):
  - "Aesthetic / Cosmetic (non-breast)"
  - "Breast"
  - "Craniofacial"
  - "Hand/Upper extremity & Peripheral Nerve"
  - "Burn"
  - "Generalized Cutaneous Disorders"
  - "Head & Neck Reconstruction"
  - "Trunk / Pelvic / Lower-Limb Reconstruction"
  - "Gender-affirming Surgery"
  - "Education & Technology"
  - "Other" (specify in subspecialty_focus_other)

  FIELD 3 - Priority Topics (SELECT ONE):
  
    • Gluteal Fat Grafting Safety (incl. BBL mortality risk)
      • Liposuction Safety
      • ADM (Acellular Dermal Matrix) Safety Updates
      • Injectable Fillers Safety
      • Malignant Hyperthermia
      • Ambulatory Surgery Adverse Event Prevention
      • Breast Implant-Associated Anaplastic Large Cell Lymphoma (BIA-ALCL)
      • FDA Warning: Silicone Injection
      • Administration of Botulinum Toxin Neuromodulators
      • Breast Augmentation in Teenagers
      • Social Media Ethics
      • Artificial Intelligence (AI) in Plastic Surgery
      • Telemedicine and Virtual Care
      • Regenerative Medicine (incl. Stem Cells and Fat Grafting)
      • Opioid Prescribing
      • Economic Evaluations
       • Breast Cancer Patient Education Act
      • Ensuring Lasting Smiles Act
      • Global Surgery / Access to Reconstructive Care
      • Diversity, Equity, and Inclusion (DEI)
      • Resident and Physician Wellness
      • Migraine Headache Surgery
      • Overseas Surgery Complications and Ethics


  Important Guidelines:
  - For Field 1: Choose the SINGLE most appropriate study design
  - For Field 2: Choose the SINGLE most appropriate subspecialty focus
  - For Field 3:  Choose the SINGLE most appropriate priority topic 

  - Use "Other" with explanation when content doesn't clearly fit predefined categories
  - Base all classifications on the abstract content and title
  - If uncertain, use "Other" and provide reasoning rather than forcing a poor fit
